stages:
    - test
    - publish

image: node:latest

cache:
  paths:
    - node_modules/
      
test:
  stage: test
  tags:
    - docker
  script:
    - npm install
    - npm link
    - npm test

publish:
  stage: publish
  tags:
    - docker
  script:
    - npm install
    - npm run publish
  only:
    - tags
